# Fabric versions see: https://fabricmc.net/develop
# Forge versions see: https://files.minecraftforge.net
# NeoForge versions see: https://neoforged.net
# Extra dependencies see: https://linkie.shedaniel.dev/dependencies

["1.16.5"]
cloth_config="4.17.132"
fabric_api="0.42.0+1.16"
modmenu="1.16.23"
appleskin="mc1.16.5-2.5.1"
pub_start="1.16"

["1.17.1"]
cloth_config="5.3.63"
fabric_api="0.46.1+1.17"
modmenu="2.0.17"
appleskin="mc1.17.1-2.5.1"
pub_start="1.17"
pub_end="1.19.2"

["1.19.4"]
cloth_config="10.1.135"
fabric_api="0.87.2+1.19.4"
modmenu="6.3.1"
appleskin="mc1.19.4-2.5.1"
pub_start="1.19.3"

["1.20.1"]
cloth_config="11.1.136"
fabric_api="0.92.7+1.20.1"
modmenu="7.2.2"
appleskin="mc1.20-2.5.1"
pub_start="1.20"

["1.20.2"]
cloth_config="12.0.137"
fabric_api="0.91.6+1.20.2"
modmenu="8.0.1"
appleskin="mc1.20.2-2.5.1"
pub_end="1.20.4"

["1.20.6"]
cloth_config="14.0.139"
fabric_api="0.100.8+1.20.6"
modmenu="10.0.0"
appleskin="mc1.20.5-3.0.5"
pub_start="1.20.5"

["1.21.1"]
neoforge="218"
cloth_config="15.0.140"
fabric_api="0.116.8+1.21.1"
modmenu="11.0.3"
appleskin="mc1.21-3.0.6"
pub_start="1.21"

["1.21.1-neoforge"]
appleskin="mc1.21-3.0.7"

["1.21.3"]
neoforge="95"
cloth_config="16.0.143"
fabric_api="0.114.1+1.21.3"
modmenu="12.0.0"
appleskin="mc1.21.3-3.0.6"
pub_start="1.21.2"
pub_end="1.21.4"

["1.21.3-neoforge"]
appleskin="mc1.21.3-3.0.7"

["1.21.5"]
neoforge="88"
cloth_config="18.0.145"
fabric_api="0.128.2+1.21.5"
modmenu="14.0.1"
appleskin="mc1.21.5-3.0.6"

["1.21.5-neoforge"]
appleskin="mc1.21.5-3.0.7"

["1.21.8"]
neoforge="42"
cloth_config="19.0.147"
fabric_api="0.136.1+1.21.8"
modmenu="15.0.1"
appleskin="mc1.21.6-3.0.6"
pub_start="1.21.6"
pub_end="1.21.10"

["1.21.8-neoforge"]
appleskin="mc1.21.6-3.0.7"

["1.21.11"]
neoforge="19-beta"
cloth_config="21.11.153"
fabric_api="0.141.2+1.21.11"
modmenu="17.0.0-beta.2"
appleskin="mc1.21.11-3.0.7"

["26.1"]
version="26.1-pre-2"
fabric_api="0.143.15+26.1"
modmenu="18.0.0-alpha.6"
pub_end="latest"
